---
repo:
  private:
    force: 1
    gpg: [ "11111111", "AAAAAAAA", "BBBBBBBB" ]
    pull_url: https://some/repo

  public:
    force: 1
    gpg: [ "DDDDDDDD", "DDDDDDDD", "BBBBBBBB" ]
    pull_url: https://some/other/repo


# in which order load repos in module/hiera path
use_repos:
  - private
  - public

# which repo should be used to source manifest
manifest_from: private


# repo dir is work_dir + /repos by default
# repo_dir: /var/lib/dpp/repos
work_dir: /var/lib/dpp

# how often we should poll each url
poll_interval: 600

puppet:
   # wait that many seconds before first run
  start_wait: 20
  # minimum of seconds to wait between puppet runs
  minimum_interval: 120
  # how ofter puppet should be run if no config changes ?
  schedule_run: 3600
