---
repo:
  private:
    branch: master
    check_url: http://dpp.devrandom.pl/puppet.html
    force: 1
    gpg: [ "AAAAAAAA", "BBBBBBBB", "CCCCCCCC" ]
    hiera_dir: hiera
    pull_url: https://some:apikey@github.com/some/repo.git

  public:
    branch: master
    check_url: http://github.toolbox.zxz.li/repo/puppet-modules
    force: 1
    gpg: [ "FFFFFFFF", "EEEEEEEE", "DDDDDDDD" ]
    pull_url: https://github.com/some/other-repo.git

# in which order load repos in module/hiera path
use_repos:
  - private
  - shared

manifest_from: shared
repo_dir: /var/lib/dpp/repos

#TODO manager url
#manager_url: http://dppd. not implemented yet
# how often we should poll each url
poll_interval: 600

puppet:
   # wait that many seconds before first run
  start_wait: 20
  # minimum of seconds to wait between puppet runs
  minimum_interval: 120
  # how ofter puppet should be run if no config changes ?
  schedule_run: 3600

# if defined will save pid in that file
# TODO
#pid_file: /var/run/dpp.pid

# TODO shows if last poll gave us new commit or if it failed
#status_file: /tmp/dpp.status


log:
#    ansicolor: 0
#    target: syslog
