---
name: Release

on:
  push:
    tags:
    - 'v*'
jobs:
    test:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - run: go test -v ./...
    build:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - run: make arch
      - uses: ncipollo/release-action@v1
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "bin/*"